version: "3.6"
services:
  ofer-server:
    image: ofer-server
    container_name: ofer-server
    build: ./ofer-server
    ports:
      - 4000:4000
    volumes:
      - ./ofer-server/:/usr/src/app/
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_HOST: ofer-db
      NODE_ENV: dev
      NODE_PORT: 4000
    command: npm run start:watch
    links:
      - ofer-db
    depends_on:
      - ofer-db
    networks:
      - esnet
    healthcheck:
      test: "pwd; ls -la; cat /etc/hosts; ping -c10 ofer-db"
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      - ofer-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ofer-db
      PMA_USER: aaa
      PMA_PASSWORD: aaa
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - esnet

  ofer-db:
    image: mariadb:10.4.14
    container_name: ofer-db
    volumes:
      - ./ofer-db/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: testDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: localhost
      NODE_ENV: dev
    ports:
      - 3306:3306
    healthcheck:
      test: '/usr/bin/mysql -h localhost --user=root --password=my-secret-pw --execute "SHOW DATABASES;"'
      timeout: 20s
      retries: 10
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - esnet

networks:
  esnet:
